### ISSUE TITLE
SalesForce connector QueryMore action is not working

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/connectors#104]
When trying to run the queryMore action of the sample.bal, following error occured
`error in ballerina program: failed to create xml: Undeclared namespace prefix "urn"
 at [row,col {unknown-source}]: [1,15]
	 at queryMore(samples.bal:63)
	 at main(samples.bal:5)
`

**Comment by kesavany** [comment]
This is fixed in https://github.com/ballerinalang/connectors/pull/98
