### ISSUE TITLE
SalesForceRest connector sObjectDescribe is not working

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/connectors#117]
According to [1] the $subject URI should be /vXX.X/sobjects/SObjectName/describe/

But in the current connector implementation the URI does not set up to /describe as shown below

`    @doc:Description{ value : "Completely describes the individual metadata at all levels for the specified object"}
    @doc:Param{ value : "sf: The salesforcerest connector instance"}
    @doc:Param{ value : "apiVersion: The api version to send request to"}
    @doc:Param{ value : "sobjectName: The relevant sobject name"}
    @doc:Return{ value : "response message"}
    action sObjectDescribe(ClientConnector sf, string sobjectName, string apiVersion) (message) {
        string httpMethod;
        string requestURI;
        message requestMsg = {};
        message response = {};
        requestURI = "/services/data/" + apiVersion + "/sobjects/" + sobjectName;
        response = oauth2:ClientConnector.get(oauth2Connector, requestURI, requestMsg);
        return response;
    }`

Hence the invocation fails as given below
[{"errorCode":"NOT_FOUND","message":"The requested resource does not exist"}]

**Comment by hariss63** [comment]
fixed in https://github.com/ballerinalang/connectors/pull/118/commits/e2ee7c5b5a67f434f5ad34606a268672891e9569
