### ISSUE TITLE
SalesforceRest connector sObjectGetUpdated action is not working correctly

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/connectors#119]
In the connector implementation, the sObjectGetUpdated is refering to the resource /deleted as shown below

` @doc:Description{ value : "Retrieves the list of individual records that have been updated (added or changed)
     within the given timespan for the specified object"}
    @doc:Param{ value : "sf: The salesforcerest connector instance"}
    @doc:Param{ value : "apiVersion: The api version to send request to"}
    @doc:Param{ value : "sobjectName: The relevant sobject name"}
    @doc:Param{ value : "startTime: The start time of the time span"}
    @doc:Param{ value : "endTime: The end time of the time span"}
    @doc:Return{ value : "response message"}
    action sObjectGetUpdated(ClientConnector sf, string apiVersion, string sobjectName, string startTime, string endTime) (message)
     {
        string httpMethod;
        string requestURI;
        message requestMsg = {};
        message response = {};
        requestURI = "/services/data/" + apiVersion + "/sobjects/" + sobjectName + "/deleted/?start=" + uri:encode(startTime)
        + "&end=" + uri:encode(endTime);
        response = oauth2:ClientConnector.get(oauth2Connector, requestURI, requestMsg);
        return response;
    }`

This should be changed to **/updated** as per the api documentation [1] 

[1] https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_getupdated.htm

**Comment by kesavany** [comment]
Fixed in https://github.com/ballerinalang/connectors/pull/120.
