### ISSUE TITLE
SalesForceRest connector update action throws a carbon exception in testerina test

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/connectors#122]
I have the following code to implement the update function
`function testUpdate(){
    string args1 = "v32.0";
    string args2 = "0012800001IoxHMAAZ";
    json sampleUpdate = {"Name":"TestUpdate"};
    salesforcerest:ClientConnector connectorInstance = init();
    response = salesforcerest:ClientConnector.update(connectorInstance, args1, "Account", args2, sampleUpdate);
    JSONResponse = messages:getJsonPayload(response);
    string statusCode = (string)http:getStatusCode(response);
    test:assertTrue(strings:equalsIgnoreCase(statusCode, "200"));
}`

It throws the following error
` testUpdate: Failed to get json payload: failed to create json: No content to map due to end-of-input
 at [Source: org.wso2.carbon.messaging.CarbonMessage$ByteBufferInputStream@f9879ac; line: 1, column: 1]
`

**Comment by kesavany** [comment]
There is no payload to build as JSON since we get 204 response from Salesforce. So we can remove the 
 JSONResponse = messages:getJsonPayload(response);
