### ISSUE TITLE
Error when special characters are included in the fields parameter of the "getIssueInfo" of the JIRA connector

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/connectors#127]
**Steps**
1. Run the getIssueInfo action of the JIRA connector as below passing "*all,-comment" or "*all" [1] for "fields"

bin$ ./ballerina run main samples.bal getIssueInfo <apiInstance:-Required> <username:-Required> <password:-Required> <issueIdOrKey:-Required> <expand:-Optional> <fields:-Optional>

**Issue**
The following error is thrown 
```
error in ballerina program: failed to get json payload: failed to create json: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.wso2.carbon.messaging.CarbonMessage$ByteBufferInputStream@f107c50; line: 1, column: 2]
	 at ballerina.lang.messages:getJsonPayload(samples.bal:18)
	 at main(samples.bal:9)
```

[1] https://developer.atlassian.com/static/rest/jira/6.1.html#d2e1160

**Comment by Biruntha** [comment]
@dilinisg
I have tested this with the latest release of ballerina (0.87) as you mentioned. It works fine.

**sample request**
./ballerina run main samples.bal getIssueInfo https://connectorwso2.atlassian.net xxxx xxxx ESBCONNECT-1 names *all

**sample response**
{
   "expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
   "id":"10000",
   "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000",
   "key":"ESBCONNECT-1",
   "names":{
      "issuetype":"Issue Type",
      "timespent":"Time Spent",
      "project":"Project",
      "customfield_10110":"Capture for JIRA browser",
      "fixVersions":"Fix Version/s",
      "customfield_10111":"Capture for JIRA operating system",
      "aggregatetimespent":"Σ Time Spent",
      "customfield_10112":"Capture for JIRA URL",
      "resolution":"Resolution",
      "customfield_10113":"Capture for JIRA screen resolution",
      "customfield_10114":"Capture for JIRA jQuery version",
      "customfield_10104":"Rank",
      "customfield_10107":"Test sessions",
      "customfield_10108":"Raised during",
      "customfield_10109":"Capture for JIRA user agent",
      "resolutiondate":"Resolved",
      "workratio":"Work Ratio",
      "watches":"Watchers",
      "lastViewed":"Last Viewed",
      "created":"Created",
      "priority":"Priority",
      "customfield_10100":"[CHART] Date of First Response",
      "customfield_10101":"[CHART] Time in Status",
      "customfield_10102":"Approvals",
      "labels":"Labels",
      "customfield_10103":"Sprint",
      "timeestimate":"Remaining Estimate",
      "aggregatetimeoriginalestimate":"Σ Original Estimate",
      "versions":"Affects Version/s",
      "issuelinks":"Linked Issues",
      "assignee":"Assignee",
      "updated":"Updated",
      "status":"Status",
      "components":"Component/s",
      "timeoriginalestimate":"Original Estimate",
      "description":"Description",
      "timetracking":"Time Tracking",
      "customfield_10006":"Epic Link",
      "customfield_10007":"Parent Link",
      "aggregatetimeestimate":"Σ Remaining Estimate",
      "attachment":"Attachment",
      "summary":"Summary",
      "creator":"Creator",
      "subtasks":"Sub-tasks",
      "reporter":"Reporter",
      "aggregateprogress":"Σ Progress",
      "customfield_10000":"Development",
      "customfield_10001":"Team",
      "customfield_10002":"Organizations",
      "environment":"Environment",
      "duedate":"Due Date",
      "progress":"Progress",
      "comment":"Comment",
      "votes":"Votes",
      "worklog":"Log Work"
   },
   "fields":{
      "issuetype":{ },
      "timespent":null,
      "project":{ },
      "customfield_10110":null,
      "fixVersions":[

      ],
      "customfield_10111":null,
      "aggregatetimespent":null,
      "customfield_10112":null,
      "resolution":null,
      "customfield_10113":null,
      "customfield_10114":null,
      "customfield_10104":"0|hzzzzz:",
      "customfield_10107":null,
      "customfield_10108":null,
      "customfield_10109":null,
      "resolutiondate":null,
      "workratio":-1,
      "watches":{ },
      "lastViewed":"2017-05-18T14:37:48.471+0530",
      "created":"2017-05-17T16:06:04.239+0530",
      "priority":{ },
      "customfield_10100":null,
      "customfield_10101":null,
      "customfield_10102":null,
      "labels":[ ],
      "customfield_10103":null,
      "timeestimate":null,
      "aggregatetimeoriginalestimate":null,
      "versions":[ ],
      "issuelinks":[ ],
      "assignee":{ },
      "updated":"2017-05-17T17:14:03.849+0530",
      "status":{ },
      "components":[ ],
      "timeoriginalestimate":null,
      "description":null,
      "timetracking":{

      },
      "customfield_10006":null,
      "customfield_10007":null,
      "aggregatetimeestimate":null,
      "attachment":[

      ],
      "summary":"issuee1",
      "creator":{ },
      "subtasks":[ ],
      "reporter":{ },
      "aggregateprogress":{ },
      "customfield_10000":"{}",
      "customfield_10001":null,
      "customfield_10002":null,
      "environment":null,
      "duedate":null,
      "progress":{ },
      "comment":{ },
      "votes":{
         "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/ESBCONNECT-1/votes",
         "votes":0,
         "hasVoted":false
      },
      "worklog":{
         "startAt":0,
         "maxResults":20,
         "total":0,
         "worklogs":[

         ]
      }
   }
}

**sample request**
./ballerina run main samples.bal getIssueInfo https://connectorwso2.atlassian.net xxx xxxx ESBCONNECT-1 names *all,-comment
/rest/api/2/issue/ESBCONNECT-1?expand=names&fields=*all,-comment

**sample response**
{
   "expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
   "id":"10000",
   "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000",
   "key":"ESBCONNECT-1",
   "names":{ },
   "fields":{
      "issuetype":{ },
      "timespent":null,
      "project":{ },
      "customfield_10110":null,
      "fixVersions":[ ],
      "aggregatetimespent":null,
      "customfield_10111":null,
      "customfield_10112":null,
      "resolution":null,
      "customfield_10113":null,
      "customfield_10114":null,
      "customfield_10104":"0|hzzzzz:",
      "customfield_10107":null,
      "customfield_10108":null,
      "customfield_10109":null,
      "resolutiondate":null,
      "workratio":-1,
      "watches":{ },
      "lastViewed":"2017-05-18T14:37:48.471+0530",
      "created":"2017-05-17T16:06:04.239+0530",
      "priority":{ },
      "customfield_10100":null,
      "customfield_10101":null,
      "customfield_10102":null,
      "labels":[ ],
      "customfield_10103":null,
      "timeestimate":null,
      "aggregatetimeoriginalestimate":null,
      "versions":[ ],
      "issuelinks":[

      ],
      "assignee":{
         "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
         "name":"admin",
         "key":"admin",
         "emailAddress":"connectorwso2@gmail.com",
         "avatarUrls":{
            "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
            "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
            "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
            "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
         },
         "displayName":"Connector Test  [Administrator]",
         "active":true,
         "timeZone":"Asia/Kolkata"
      },
      "updated":"2017-05-17T17:14:03.849+0530",
      "status":{
         "self":"https://connectorwso2.atlassian.net/rest/api/2/status/10000",
         "description":"",
         "iconUrl":"https://connectorwso2.atlassian.net/",
         "name":"To Do",
         "id":"10000",
         "statusCategory":{
            "self":"https://connectorwso2.atlassian.net/rest/api/2/statuscategory/2",
            "id":2,
            "key":"new",
            "colorName":"blue-gray",
            "name":"To Do"
         }
      },
      "components":[

      ],
      "timeoriginalestimate":null,
      "description":null,
      "timetracking":{

      },
      "customfield_10006":null,
      "customfield_10007":null,
      "attachment":[

      ],
      "aggregatetimeestimate":null,
      "summary":"issuee1",
      "creator":{
         "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
         "name":"admin",
         "key":"admin",
         "emailAddress":"connectorwso2@gmail.com",
         "avatarUrls":{
            "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
            "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
            "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
            "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
         },
         "displayName":"Connector Test  [Administrator]",
         "active":true,
         "timeZone":"Asia/Kolkata"
      },
      "subtasks":[

      ],
      "reporter":{
         "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
         "name":"admin",
         "key":"admin",
         "emailAddress":"connectorwso2@gmail.com",
         "avatarUrls":{
            "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
            "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
            "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
            "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
         },
         "displayName":"Connector Test  [Administrator]",
         "active":true,
         "timeZone":"Asia/Kolkata"
      },
      "customfield_10000":"{}",
      "aggregateprogress":{
         "progress":0,
         "total":0
      },
      "customfield_10001":null,
      "customfield_10002":null,
      "environment":null,
      "duedate":null,
      "progress":{
         "progress":0,
         "total":0
      },
      "votes":{
         "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/ESBCONNECT-1/votes",
         "votes":0,
         "hasVoted":false
      },
      "worklog":{
         "startAt":0,
         "maxResults":20,
         "total":0,
         "worklogs":[

         ]
      }
   }
}
