### ISSUE TITLE
The field parameters of the "getIssueInfo" action of the JIRA connector are not considered 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/connectors#128]
**Steps**

1. Run the getIssueInfo action of the JIRA connector as below passing "summary,comment" for "fields" and save the response.
2. Run the getIssueInfo action again passing "comment" for "fields" and save the response.
3. Compare the two responses

bin$ ./ballerina run main samples.bal getIssueInfo apiInstance:-Required username:-Required password:-Required issueIdOrKey:-Required expand:-Optional fields:-Optional

**Issue**
Both responses are same. The field parameters are not considered

**Comment by Biruntha** [comment]
@dilinisg 
I have tested this with the latest release of ballerina (0.87). It works fine.
**sample request**
./ballerina run main samples.bal getIssueInfo xxxxxx xxxx xxxxx ESBCONNECT-1 names summary,comment
**sample response**
{
   "expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
   "id":"10000",
   "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000",
   "key":"ESBCONNECT-1",
   "names":{
      "summary":"Summary",
      "comment":"Comment"
   },
   "fields":{
      "summary":"issuee1",
      "comment":{
         "comments":[
            {
               "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000/comment/10000",
               "id":"10000",
               "author":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "body":"This is comment for TES-2",
               "updateAuthor":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "created":"2017-05-17T16:20:36.226+0530",
               "updated":"2017-05-17T16:20:36.226+0530",
               "visibility":{
                  "type":"role",
                  "value":"Administrators"
               }
            },
            {
               "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000/comment/10001",
               "id":"10001",
               "author":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "body":"This is comment for TES-2",
               "updateAuthor":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "created":"2017-05-17T17:14:03.849+0530",
               "updated":"2017-05-17T17:14:03.849+0530",
               "visibility":{
                  "type":"role",
                  "value":"Administrators"
               }
            }
         ],
         "maxResults":2,
         "total":2,
         "startAt":0
      }
   }
}

**sample request**
./ballerina run main samples.bal getIssueInfo xxxxxxx xxxx xxx ESBCONNECT-1 names comment

**sample response**
{
   "expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
   "id":"10000",
   "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000",
   "key":"ESBCONNECT-1",
   "names":{
      "comment":"Comment"
   },
   "fields":{
      "comment":{
         "comments":[
            {
               "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000/comment/10000",
               "id":"10000",
               "author":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "body":"This is comment for TES-2",
               "updateAuthor":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "created":"2017-05-17T16:20:36.226+0530",
               "updated":"2017-05-17T16:20:36.226+0530",
               "visibility":{
                  "type":"role",
                  "value":"Administrators"
               }
            },
            {
               "self":"https://connectorwso2.atlassian.net/rest/api/2/issue/10000/comment/10001",
               "id":"10001",
               "author":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "body":"This is comment for TES-2",
               "updateAuthor":{
                  "self":"https://connectorwso2.atlassian.net/rest/api/2/user?username=admin",
                  "name":"admin",
                  "key":"admin",
                  "emailAddress":"connectorwso2@gmail.com",
                  "avatarUrls":{
                     "48x48":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=48",
                     "24x24":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=24",
                     "16x16":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=16",
                     "32x32":"https://secure.gravatar.com/avatar/8bc257edaf593ba8a277232a9b30552c?d=mm&s=32"
                  },
                  "displayName":"Connector Test  [Administrator]",
                  "active":true,
                  "timeZone":"Asia/Kolkata"
               },
               "created":"2017-05-17T17:14:03.849+0530",
               "updated":"2017-05-17T17:14:03.849+0530",
               "visibility":{
                  "type":"role",
                  "value":"Administrators"
               }
            }
         ],
         "maxResults":2,
         "total":2,
         "startAt":0
      }
   }
}
