### ISSUE TITLE
FB connector doc issues

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/connectors#75]
1. The parameters specified to create a post is incorrect
There are only 5 arguments that needs to be passed in the command to run
bin$ ./ballerina run main samples.bal createPost <token> <message> <link> <place>

But the createPost function refers to a 6th argument.
facebookResponse = facebook:ClientConnector.createPost(facebookConnector, args[2], args[3], args[4], args[5]);

2. Need more information as to what access token needs to be taken as there are access tokens for applications and users and the access token available in the pointed link does not work
Prerequisites:
Get the access_token from https://developers.facebook.com/tools/explorer/

**Comment by hariss63** [comment]
Yes we miss the id value

**Comment by hariss63** [comment]
Fix 55ac8ee62b6d8e7c0255854d00323fa1e6064cc4
